"use client";
import {useEffect,useMemo,useState} from "react";

type Status="Found"|"Contacted"|"Replied"|"Qualified"|"Proposal"|"Won"|"Lost";
type Lead={id:string;name:string;company:string;role:string;channel:string;problem:string;source:string;status:Status;value:number;lastContact:string;nextAction:string;notes:string;createdAt:string};
const statuses:Status[]=["Found","Contacted","Replied","Qualified","Proposal","Won","Lost"];
const emptyForm={name:"",company:"",role:"",channel:"",problem:"",source:"",value:"",nextAction:"",notes:""};
function money(n:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n)}
export default function Home(){
 const [leads,setLeads]=useState<Lead[]>([]); const [loaded,setLoaded]=useState(false); const [active,setActive]=useState<"Overview"|"Leads"|"Pipeline">("Overview"); const [show,setShow]=useState(false); const [form,setForm]=useState(emptyForm); const [filter,setFilter]=useState<Status|"All">("All");
 useEffect(()=>{try{const raw=localStorage.getItem("cashflow-os:leads");if(raw)setLeads(JSON.parse(raw))}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded)localStorage.setItem("cashflow-os:leads",JSON.stringify(leads))},[leads,loaded]);
 const stats=useMemo(()=>({total:leads.length,contacted:leads.filter(l=>["Contacted","Replied","Qualified","Proposal","Won"].includes(l.status)).length,replies:leads.filter(l=>["Replied","Qualified","Proposal","Won"].includes(l.status)).length,wins:leads.filter(l=>l.status==="Won").length,cash:leads.filter(l=>l.status==="Won").reduce((s,l)=>s+l.value,0),pipeline:leads.filter(l=>["Qualified","Proposal"].includes(l.status)).reduce((s,l)=>s+l.value,0)}),[leads]);
 const filtered=filter==="All"?leads:leads.filter(l=>l.status===filter);
 function addLead(e:React.FormEvent){e.preventDefault();if(!form.name.trim()||!form.company.trim())return;const now=new Date().toISOString();setLeads([{id:crypto.randomUUID(),name:form.name.trim(),company:form.company.trim(),role:form.role.trim(),channel:form.channel.trim(),problem:form.problem.trim(),source:form.source.trim(),status:"Found",value:Number(form.value)||0,lastContact:"",nextAction:form.nextAction.trim(),notes:form.notes.trim(),createdAt:now},...leads]);setForm(emptyForm);setShow(false);setActive("Leads")}
 function move(id:string,status:Status){setLeads(leads.map(l=>l.id===id?{...l,status,lastContact:status!=="Found"?new Date().toISOString():l.lastContact}:l))}
 return <main><aside><div className="brand"><div className="mark">C</div><div><b>Cashflow OS</b><span>sales operating system</span></div></div><nav>{(["Overview","Leads","Pipeline"] as const).map(x=><button className={active===x?"nav active":"nav"} onClick={()=>setActive(x)} key={x}><span>{x==="Overview"?"⌂":x==="Leads"?"◎":"↗"}</span>{x}</button>)}</nav><div className="sidebarBottom"><div className="goal"><span>Immediate goal</span><strong>Get paid.</strong><small>Find problems. Start conversations. Close small jobs.</small></div><button className="add" onClick={()=>setShow(true)}>+ Add lead</button></div></aside>
 <section className="content"><header><div><p className="eyebrow">FIELD SALES</p><h1>{active}</h1><p className="sub">Turn real conversations into measurable cashflow.</p></div><button className="primary" onClick={()=>setShow(true)}>+ New lead</button></header>
 {active==="Overview"&&<><div className="cards"><Card label="Leads" value={String(stats.total)} hint="people identified"/><Card label="Contacted" value={String(stats.contacted)} hint="conversations started"/><Card label="Replies" value={String(stats.replies)} hint="active conversations"/><Card label="Cash collected" value={money(stats.cash)} hint={stats.wins+" deal"+(stats.wins===1?"":"s")+" won"}/></div><div className="grid"><section className="panel"><div className="panelHead"><div><h2>Today's scoreboard</h2><p>Numbers that matter more than activity.</p></div></div><div className="score"><Score n={stats.total} label="Leads found"/><Score n={stats.contacted} label="People contacted"/><Score n={stats.replies} label="Replies"/><Score n={stats.wins} label="Deals won"/></div></section><section className="panel"><div className="panelHead"><div><h2>Pipeline value</h2><p>Potential value from qualified opportunities.</p></div></div><div className="bigMoney">{money(stats.pipeline)}</div><div className="hint">Qualified + proposal stages</div></section></div><section className="panel"><div className="panelHead"><div><h2>Next actions</h2><p>Never leave a real opportunity without a next move.</p></div><button className="textBtn" onClick={()=>setActive("Leads")}>View all →</button></div><LeadList leads={leads.filter(l=>l.nextAction).slice(0,5)} move={move}/></section></>}
 {active==="Leads"&&<section className="panel"><div className="toolbar"><div className="filters"><button className={filter==="All"?"pill selected":"pill"} onClick={()=>setFilter("All")}>All</button>{statuses.map(s=><button key={s} className={filter===s?"pill selected":"pill"} onClick={()=>setFilter(s)}>{s}</button>)}</div><span className="count">{filtered.length} lead{filtered.length===1?"":"s"}</span></div>{filtered.length?<LeadList leads={filtered} move={move}/>:<Empty onAdd={()=>setShow(true)}/>}</section>}
 {active==="Pipeline"&&<div className="kanban">{statuses.slice(0,6).map(s=><div className="column" key={s}><div className="colHead"><b>{s}</b><span>{leads.filter(l=>l.status===s).length}</span></div>{leads.filter(l=>l.status===s).map(l=><article className="leadCard" key={l.id}><strong>{l.company}</strong><span>{l.name}{l.role?" · "+l.role:""}</span>{l.problem&&<p>{l.problem}</p>}<div className="cardFoot">{l.value?money(l.value):"No value set"}<select value={l.status} onChange={e=>move(l.id,e.target.value as Status)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div></article>)}</div>)}</div>}
 </section>{show&&<div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)setShow(false)}}><form className="modal" onSubmit={addLead}><div className="modalHead"><div><p className="eyebrow">NEW OPPORTUNITY</p><h2>Add a lead</h2></div><button type="button" className="close" onClick={()=>setShow(false)}>×</button></div><div className="formGrid"><Field label="Name *" value={form.name} set={v=>setForm({...form,name:v})}/><Field label="Company *" value={form.company} set={v=>setForm({...form,company:v})}/><Field label="Role" value={form.role} set={v=>setForm({...form,role:v})}/><Field label="Contact channel" value={form.channel} set={v=>setForm({...form,channel:v})}/><Field label="Source" value={form.source} set={v=>setForm({...form,source:v})}/><Field label="Potential value (₦)" value={form.value} set={v=>setForm({...form,value:v})} type="number"/><div className="field full"><label>Problem observed</label><textarea value={form.problem} onChange={e=>setForm({...form,problem:e.target.value})} placeholder="What problem makes this person worth contacting?"/></div><Field label="Next action" value={form.nextAction} set={v=>setForm({...form,nextAction:v})}/><div className="field full"><label>Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Context, objections, conversation notes…"/></div></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancel</button><button className="primary" type="submit">Create lead</button></div></form></div>}</main>}
function Card({label,value,hint}:{label:string;value:string;hint:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>}; function Score({n,label}:{n:number;label:string}){return <div><strong>{n}</strong><span>{label}</span></div>};
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div className="field"><label>{label}</label><input type={type} value={value} onChange={e=>set(e.target.value)} placeholder={label.replace(" *","")}/></div>}
function LeadList({leads,move}:{leads:Lead[];move:(id:string,status:Status)=>void}){if(!leads.length)return <Empty/>;return <div className="leadList">{leads.map(l=><div className="row" key={l.id}><div className="avatar">{l.company.slice(0,1).toUpperCase()}</div><div className="leadMain"><strong>{l.company}</strong><span>{l.name}{l.role?" · "+l.role:""}</span>{l.problem&&<small>{l.problem}</small>}</div><div className="rowAction">{l.nextAction&&<span className="next">{l.nextAction}</span>}<select value={l.status} onChange={e=>move(l.id,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div>)}</div>}
function Empty({onAdd=()=>{}}:{onAdd?:()=>void}){return <div className="empty"><div className="emptyIcon">+</div><h3>No leads yet</h3><p>Your first job is finding one person with a problem you can solve.</p><button className="primary" onClick={onAdd}>Add your first lead</button></div>}